import { applyDecorators } from '@nestjs/common';
import { ApiBearerAuth, ApiOkResponse, ApiOperation } from '@nestjs/swagger';

export function DocsContractFindAOne() {
  return applyDecorators(
    ApiOperation({
      summary: 'Obtener un solo contracto',
      description: 'obtener los datos del contracto',
    }),
    ApiBearerAuth(),
    ApiOkResponse({
      content: {
        'application/json': {
          schema: {
            type: 'object',
          },
          example: {
            id: '52b0c87f-6c11-4170-89e7-6d34e9bb43c4',
            folder: '',
            number: '',
            correlative: 1,
            client: {
              id: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
              email: 'alexaguilar281@gmail.com',
              roles: [],
              profile: {
                document: 'C.E.',
                documentNumber: '987654321',
                name: 'Alejandro',
                secondName: '',
                lastName: 'Aguilar',
                secondLastName: '',
                phone: '51939130496',
                gender: 'male',
                birthDate: '2024-05-23T07:21:24.988Z',
                department: '',
                province: '',
                district: '',
                direction: '',
                _id: '664eee75ff216f66b38533b9',
              },
              user: '',
              status: 'active',
              auth: {
                admin: true,
                rememberToken: '',
                lastLogin: null,
                _id: '664eee75ff216f66b38533ba',
              },
              linkWhatsApp: '',
              isAdvisor: true,
              isDoctor: false,
            },
            details: [
              {
                id: 'fe376d6c-cf00-4488-aa9f-ef32e8b57e01',
                documentation: {
                  status: 'pending',
                  clientStatus: 'pending',
                  vaccinationCertificate: {
                    isApplied: false,
                    hasServiceIncluded: true,
                    expectedDate: '2024-05-23T07:29:25.302Z',
                    executionDate: null,
                    resultDate: null,
                    isRequired: true,
                    observation: '',
                    isPrint: false,
                    user: '',
                  },
                  healthCertificate: {
                    isApplied: false,
                    hasServiceIncluded: false,
                    expectedDate: '2024-05-23T07:29:25.302Z',
                    executionDate: null,
                    resultDate: null,
                    isRequired: true,
                    observation: '',
                    isPrint: false,
                    user: '',
                  },
                  chipCertificate: {
                    isApplied: false,
                    hasServiceIncluded: true,
                    expectedDate: '2024-05-23T07:29:25.301Z',
                    executionDate: null,
                    resultDate: null,
                    isRequired: true,
                    observation: '',
                    isPrint: false,
                    user: '',
                  },
                  senasaDocuments: {
                    isApplied: false,
                    hasServiceIncluded: false,
                    expectedDate: '2024-05-23T07:29:25.303Z',
                    executionDate: null,
                    resultDate: null,
                    isRequired: true,
                    observation: '',
                    isPrint: false,
                    user: '',
                  },
                  rabiesSeroLogicalTest: {
                    isApplied: false,
                    hasServiceIncluded: true,
                    expectedDate: '2024-05-23T07:29:25.302Z',
                    executionDate: null,
                    resultDate: null,
                    isRequired: true,
                    observation: '',
                    isPrint: false,
                    user: '',
                  },
                  importLicense: {
                    isApplied: false,
                    hasServiceIncluded: false,
                    expectedDate: '2024-05-23T07:29:25.302Z',
                    executionDate: null,
                    resultDate: null,
                    isRequired: true,
                    observation: '',
                    isPrint: false,
                    user: '',
                  },
                  emotionalSupportCertificate: {
                    isApplied: false,
                    hasServiceIncluded: false,
                    expectedDate: '2024-05-23T07:29:25.303Z',
                    executionDate: null,
                    resultDate: null,
                    isRequired: false,
                    observation: '',
                    isPrint: false,
                    user: '',
                  },
                },
                cage: {
                  status: 'pending',
                  hasServiceIncluded: false,
                  chosen: {
                    modelCage: '',
                    typeCage: '',
                    dimensionsCage: '',
                    user: '',
                  },
                  confirmation: false,
                  petTravelAcquisition: false,
                  isCabinTransporting: false,
                },
                travel: {
                  status: 'pending',
                  hasServiceIncluded: true,
                  hasServiceAccompanied: false,
                  typeTraveling: 'charge',
                  airlineReservation: {
                    code: '',
                    flightNumber: '',
                    departureAirport: '',
                    destinationAirport: '',
                    departureDate: null,
                    itinerary: '',
                    arrivalDate: null,
                    archive: '',
                    user: '',
                  },
                  petPerCharge: {
                    name: '',
                    document: '',
                    documentNumber: '',
                    phone: '',
                    email: '',
                  },
                  accompaniedPet: {
                    name: '',
                    document: '',
                    documentNumber: '',
                    phone: '',
                    email: '',
                    direction: '',
                    district: '',
                    province: '',
                    department: '',
                    image: '',
                  },
                  destination: {
                    countryDestination: 'España',
                    cityDestination: '',
                    directionDestination: '',
                  },
                  guideNumber: '',
                  observation: '',
                },
                user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                topico: {
                  chip: {
                    hasIncluded: false,
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '',
                  },
                  vaccination: {
                    hasIncluded: false,
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '',
                  },
                  rabiesVaccination: {
                    hasIncluded: false,
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '',
                  },
                  rabiesReVaccination: {
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '',
                  },
                  chipReview: {
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '',
                  },
                  takingSampleSerologicalTest: {
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    typeSample: '',
                    user: '',
                  },
                },
              },
            ],
            status: {
              petTravel: 'pending',
              client: 'pending',
              _id: '664ef061c76176a5a8d56010',
            },
            startDate: '2024-05-23T07:29:16.430Z',
            estimatedDate: '2024-11-19T08:29:16.430Z',
            endDate: null,
            adviser: {
              id: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
              email: 'alexaguilar281@gmail.com',
              roles: [],
              profile: {
                document: 'C.E.',
                documentNumber: '987654321',
                name: 'Alejandro',
                secondName: '',
                lastName: 'Aguilar',
                secondLastName: '',
                phone: '51939130496',
                gender: 'male',
                birthDate: '2024-05-23T07:21:24.988Z',
                department: '',
                province: '',
                district: '',
                direction: '',
                _id: '664eee75ff216f66b38533b9',
              },
              user: '',
              status: 'active',
              auth: {
                admin: true,
                rememberToken: '',
                lastLogin: null,
                _id: '664eee75ff216f66b38533ba',
              },
              linkWhatsApp: '',
              isAdvisor: true,
              isDoctor: false,
            },
            price: 500,
            payInInstallments: [
              {
                price: 500,
                percentage: 100,
                date: '2024-05-23T07:29:16.430Z',
                isPay: true,
                customerPayments: [
                  {
                    price: 500,
                    date: '2024-05-23T07:29:16.430Z',
                    method: '',
                    _id: '664ef061c76176a5a8d56012',
                  },
                ],
                _id: '664ef061c76176a5a8d56011',
              },
            ],
            finishClient: false,
            reasonForCancellation: '',
            format: 'Europa',
            user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
          },
        },
      },
    }),
  );
}
