import { applyDecorators } from '@nestjs/common';
import { ApiBearerAuth, ApiOkResponse, ApiOperation } from '@nestjs/swagger';

export function DocsDetailFindAOne() {
  return applyDecorators(
    ApiOperation({
      summary: 'Obtener un solo contracto',
      description: 'obtener los datos del contracto',
    }),
    ApiBearerAuth(),
    ApiOkResponse({
      content: {
        'application/json': {
          schema: {
            type: 'object',
          },
          example: {
            id: '8fbaade4-d3fc-4a9d-a850-5a2c0d3de817',
            documentation: {
              status: 'pending',
              clientStatus: 'pending',
              vaccinationCertificate: {
                isApplied: false,
                hasServiceIncluded: true,
                expectedDate: '2024-05-23T07:29:55.799Z',
                executionDate: null,
                resultDate: null,
                isRequired: true,
                observation: '',
                isPrint: false,
                user: '',
              },
              healthCertificate: {
                isApplied: false,
                hasServiceIncluded: false,
                expectedDate: '2024-05-23T07:29:55.799Z',
                executionDate: null,
                resultDate: null,
                isRequired: true,
                observation: '',
                isPrint: false,
                user: '',
              },
              chipCertificate: {
                isApplied: false,
                hasServiceIncluded: true,
                expectedDate: '2024-05-23T07:29:55.799Z',
                executionDate: null,
                resultDate: null,
                isRequired: true,
                observation: '',
                isPrint: false,
                user: '',
              },
              senasaDocuments: {
                isApplied: false,
                hasServiceIncluded: false,
                expectedDate: '2024-05-23T07:29:55.800Z',
                executionDate: null,
                resultDate: null,
                isRequired: true,
                observation: '',
                isPrint: false,
                user: '',
              },
              rabiesSeroLogicalTest: {
                isApplied: false,
                hasServiceIncluded: true,
                expectedDate: '2024-05-23T07:29:55.799Z',
                executionDate: null,
                resultDate: null,
                isRequired: true,
                observation: '',
                isPrint: false,
                user: '',
              },
              importLicense: {
                isApplied: false,
                hasServiceIncluded: false,
                expectedDate: '2024-05-23T07:29:55.799Z',
                executionDate: null,
                resultDate: null,
                isRequired: true,
                observation: '',
                isPrint: false,
                user: '',
              },
              emotionalSupportCertificate: {
                isApplied: false,
                hasServiceIncluded: false,
                expectedDate: '2024-05-23T07:29:55.800Z',
                executionDate: null,
                resultDate: null,
                isRequired: false,
                observation: '',
                isPrint: false,
                user: '',
              },
            },
            cage: {
              status: 'pending',
              hasServiceIncluded: false,
              chosen: {
                modelCage: '',
                typeCage: '',
                dimensionsCage: '',
                user: '',
              },
              confirmation: false,
              petTravelAcquisition: false,
              isCabinTransporting: false,
            },
            travel: {
              status: 'pending',
              hasServiceIncluded: true,
              hasServiceAccompanied: false,
              typeTraveling: 'charge',
              airlineReservation: {
                code: '',
                flightNumber: '',
                departureAirport: '',
                destinationAirport: '',
                departureDate: null,
                itinerary: '',
                arrivalDate: null,
                archive: '',
                user: '',
              },
              petPerCharge: {
                name: '',
                document: '',
                documentNumber: '',
                phone: '',
                email: '',
              },
              accompaniedPet: {
                name: '',
                document: '',
                documentNumber: '',
                phone: '',
                email: '',
                direction: '',
                district: '',
                province: '',
                department: '',
                image: '',
              },
              destination: {
                countryDestination: 'España',
                cityDestination: '',
                directionDestination: '',
              },
              guideNumber: '',
              observation: '',
            },
            pet: '',
            user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
            topico: {
              chip: {
                hasIncluded: false,
                executed: false,
                date: null,
                description: '',
                observation: '',
                user: '',
              },
              vaccination: {
                hasIncluded: false,
                executed: false,
                date: null,
                description: '',
                observation: '',
                user: '',
              },
              rabiesVaccination: {
                hasIncluded: false,
                executed: false,
                date: null,
                description: '',
                observation: '',
                user: '',
              },
              rabiesReVaccination: {
                executed: false,
                date: null,
                description: '',
                observation: '',
                user: '',
              },
              chipReview: {
                executed: false,
                date: null,
                description: '',
                observation: '',
                user: '',
              },
              takingSampleSerologicalTest: {
                executed: false,
                date: null,
                description: '',
                observation: '',
                typeSample: '',
                user: '',
              },
            },
          },
        },
      },
    }),
  );
}
