import { applyDecorators } from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiResponse,
  ApiOperation,
  ApiBody,
} from '@nestjs/swagger';
import { TopicoDto } from '../dto/topico/topico.dto';

export function DocsDetailUpdateTopico() {
  return applyDecorators(
    ApiOperation({
      summary: 'Actualizar detalles de topico',
    }),
    ApiBearerAuth(),
    ApiBody({
      type: TopicoDto,
      examples: {
        data: {
          value: {
            chip: {
              hasIncluded: true,
              executed: true,
              date: '2022-01-01',
              description: 'Chip contract description',
              observation: 'Chip contract observation',
            },
            vaccination: {
              hasIncluded: true,
              executed: true,
              date: '2022-02-01',
              description: 'Vaccination contract description',
              observation: 'Vaccination contract observation',
            },
            rabiesVaccination: {
              hasIncluded: true,
              executed: true,
              date: '2022-03-01',
              description: 'Rabies Vaccination contract description',
              observation: 'Rabies Vaccination contract observation',
            },
            rabiesReVaccination: {
              executed: true,
              date: '2022-04-01',
              description: 'Rabies Re-Vaccination contract description',
              observation: 'Rabies Re-Vaccination contract observation',
            },
            chipReview: {
              executed: true,
              date: '2022-05-01',
              description: 'Chip Review contract description',
              observation: 'Chip Review contract observation',
            },
            takingSampleSerologicalTest: {
              executed: true,
              date: '2022-06-01',
              description:
                'Taking Sample Serological Test contract description',
              observation:
                'Taking Sample Serological Test contract observation',
              typeSample: 'Blood',
            },
          },
        },
      },
    }),
    ApiResponse({
      status: 200,
      content: {
        'application/json': {
          schema: {
            type: 'object',
          },
          example: {
            contract: {
              id: '575be9b1-8654-478c-9a5d-7a312515e17e',
              folder: 'Folder1',
              number: '1',
              correlative: 2,
              client: {
                id: '9b548ef0-809f-4e8a-8565-3c9242a2c400',
                email: 'crichrissuarez82@gmail.com',
                roles: [],
                profile: {
                  document: 'D.N.I.',
                  documentNumber: '41233194',
                  name: 'Christian',
                  secondName: '',
                  lastName: 'Suarez',
                  secondLastName: '',
                  phone: '51994748870',
                  gender: 'male',
                  birthDate: '2024-05-23T07:21:24.988Z',
                  department: '',
                  province: '',
                  district: '',
                  direction: '',
                  _id: '664eee75ff216f66b38533bc',
                },
                user: '',
                status: 'active',
                auth: {
                  admin: true,
                  rememberToken: '',
                  lastLogin: null,
                  _id: '664eee75ff216f66b38533bd',
                },
                linkWhatsApp: '',
                isAdvisor: true,
                isDoctor: false,
              },
              details: [
                {
                  id: '8fbaade4-d3fc-4a9d-a850-5a2c0d3de817',
                  documentation: {
                    status: 'pending',
                    clientStatus: 'pending',
                    vaccinationCertificate: {
                      isApplied: false,
                      hasServiceIncluded: true,
                      expectedDate: '2024-05-23T07:29:55.799Z',
                      executionDate: null,
                      resultDate: null,
                      isRequired: true,
                      observation: '',
                      isPrint: false,
                      user: '',
                    },
                    healthCertificate: {
                      isApplied: true,
                      hasServiceIncluded: true,
                      expectedDate: '2022-06-01T00:00:00.000Z',
                      executionDate: '2022-05-30T00:00:00.000Z',
                      resultDate: '2022-05-31T00:00:00.000Z',
                      isRequired: false,
                      observation: 'All documentation is in order.',
                      isPrint: false,
                      user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    },
                    chipCertificate: {
                      isApplied: false,
                      hasServiceIncluded: true,
                      expectedDate: '2024-05-23T07:29:55.799Z',
                      executionDate: null,
                      resultDate: null,
                      isRequired: true,
                      observation: '',
                      isPrint: false,
                      user: '',
                    },
                    senasaDocuments: {
                      isApplied: true,
                      hasServiceIncluded: true,
                      expectedDate: '2022-06-01T00:00:00.000Z',
                      executionDate: '2022-05-30T00:00:00.000Z',
                      resultDate: '2022-05-31T00:00:00.000Z',
                      isRequired: false,
                      observation: 'All documentation is in order.',
                      isPrint: false,
                      user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    },
                    rabiesSeroLogicalTest: {
                      isApplied: false,
                      hasServiceIncluded: true,
                      expectedDate: '2024-05-23T07:29:55.799Z',
                      executionDate: null,
                      resultDate: null,
                      isRequired: true,
                      observation: '',
                      isPrint: false,
                      user: '',
                    },
                    importLicense: {
                      isApplied: true,
                      hasServiceIncluded: true,
                      expectedDate: '2022-06-01T00:00:00.000Z',
                      executionDate: '2022-05-30T00:00:00.000Z',
                      resultDate: '2022-05-31T00:00:00.000Z',
                      isRequired: false,
                      observation: 'All documentation is in order.',
                      isPrint: false,
                      user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    },
                    emotionalSupportCertificate: {
                      isApplied: true,
                      hasServiceIncluded: true,
                      expectedDate: '2022-06-01T00:00:00.000Z',
                      executionDate: '2022-05-30T00:00:00.000Z',
                      resultDate: '2022-05-31T00:00:00.000Z',
                      isRequired: false,
                      observation: 'All documentation is in order.',
                      isPrint: false,
                      user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    },
                  },
                  cage: {
                    status: 'completed',
                    hasServiceIncluded: true,
                    chosen: {
                      modelCage: 'Deluxe Pet Carrier',
                      typeCage: 'Soft-sided',
                      dimensionsCage: '18 x 12 x 12 inches',
                      user: '',
                    },
                    confirmation: true,
                    petTravelAcquisition: true,
                    isCabinTransporting: false,
                  },
                  travel: {
                    status: 'completed',
                    hasServiceIncluded: false,
                    hasServiceAccompanied: false,
                    typeTraveling: 'accompanied',
                    airlineReservation: {
                      code: 'A001',
                      flightNumber: '4005',
                      departureAirport: 'Lima, Peru',
                      destinationAirport: 'Buenos aires',
                      departureDate: '2022-06-01T00:00:00.000Z',
                      itinerary: '',
                      arrivalDate: '2022-06-01T00:00:00.000Z',
                      archive: '',
                      user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    },
                    petPerCharge: {
                      name: 'pedro',
                      document: 'D.N.I.',
                      documentNumber: '123456789',
                      phone: '51939130496',
                      email: 'pedro@gmail.com',
                    },
                    accompaniedPet: {
                      name: 'pedro',
                      document: 'D.N.I.',
                      documentNumber: '123456789',
                      phone: '51939130496',
                      email: 'pedro@gmail.com',
                      direction: 'Turin 457',
                      district: 'San martin de porres',
                      province: 'Lima',
                      department: 'Lima',
                      image: 'user.png',
                    },
                    destination: {
                      countryDestination: 'España',
                      cityDestination: 'Barcelona',
                      directionDestination: 'Paseo de gracia',
                    },
                    guideNumber: '',
                    observation: '',
                  },
                  pet: {
                    id: 'eacec100-1552-4712-841c-eb1f68cc13d6',
                    name: 'Terminal 01',
                    race: 'Mestizo',
                    gender: 'male',
                    birthDate: '2024-05-24T11:55:09.571Z',
                    chip: '',
                    chipDate: null,
                    color: 'Blanco',
                    image: '',
                    country: 'Perú',
                    type: 'Canino',
                    sterilized: 'No',
                    status: 'active',
                    adopter: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    isBrachycephalic: false,
                    isPotentiallyDangerous: false,
                    topico: {
                      chip: {
                        hasIncluded: false,
                        executed: false,
                        date: null,
                        description: '',
                        observation: '',
                        user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                      },
                      vaccination: {
                        hasIncluded: false,
                        executed: false,
                        date: null,
                        description: '',
                        observation: '',
                        user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                      },
                      rabiesVaccination: {
                        hasIncluded: false,
                        executed: false,
                        date: null,
                        description: '',
                        observation: '',
                        user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                      },
                      rabiesReVaccination: {
                        executed: false,
                        date: null,
                        description: '',
                        observation: '',
                        user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                      },
                      takingSampleSerologicalTest: {
                        executed: false,
                        date: null,
                        description: '',
                        observation: '',
                        typeSample: '',
                        user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                      },
                      _id: '66508031d086871037003832',
                    },
                    user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    cageRecommendation: {
                      modelCage: '',
                      typeCage: '',
                      dimensionsCage: '',
                      _id: '66508031d086871037003833',
                    },
                    measurementsAndWeight: {
                      weight: 0,
                      height: 0,
                      width: 0,
                      length: 0,
                      _id: '66508031d086871037003834',
                    },
                  },
                  user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                  topico: {
                    chip: {
                      hasIncluded: true,
                      executed: true,
                      date: '2022-01-01T00:00:00.000Z',
                      description: 'Chip contract description',
                      observation: 'Chip contract observation',
                      user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                    },
                    vaccination: {
                      hasIncluded: false,
                      executed: false,
                      date: null,
                      description: '',
                      observation: '',
                      user: '',
                    },
                    rabiesVaccination: {
                      hasIncluded: false,
                      executed: false,
                      date: null,
                      description: '',
                      observation: '',
                      user: '',
                    },
                    rabiesReVaccination: {
                      executed: false,
                      date: null,
                      description: '',
                      observation: '',
                      user: '',
                    },
                    chipReview: {
                      executed: false,
                      date: null,
                      description: '',
                      observation: '',
                      user: '',
                    },
                    takingSampleSerologicalTest: {
                      executed: false,
                      date: null,
                      description: '',
                      observation: '',
                      typeSample: '',
                      user: '',
                    },
                  },
                },
              ],
              status: {
                petTravel: 'pending',
                client: 'pending',
                _id: '665080a0e0dfe31074a2e5d6',
              },
              startDate: '2024-05-23T07:29:16.430Z',
              estimatedDate: '2024-11-19T08:29:16.430Z',
              endDate: null,
              adviser: {
                id: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                email: 'alexaguilar281@gmail.com',
                roles: [],
                profile: {
                  document: 'C.E.',
                  documentNumber: '987654321',
                  name: 'Alejandro',
                  secondName: '',
                  lastName: 'Aguilar',
                  secondLastName: '',
                  phone: '51939130496',
                  gender: 'male',
                  birthDate: '2024-05-23T07:21:24.988Z',
                  department: '',
                  province: '',
                  district: '',
                  direction: '',
                  _id: '664eee75ff216f66b38533b9',
                },
                user: '',
                status: 'active',
                auth: {
                  admin: true,
                  rememberToken: '',
                  lastLogin: null,
                  _id: '664eee75ff216f66b38533ba',
                },
                linkWhatsApp: '',
                isAdvisor: true,
                isDoctor: false,
              },
              price: 400,
              payInInstallments: [],
              finishClient: true,
              reasonForCancellation: '',
              format: 'Europa',
              user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
            },
            contractDetail: {
              id: '8fbaade4-d3fc-4a9d-a850-5a2c0d3de817',
              documentation: {
                status: 'pending',
                clientStatus: 'pending',
                vaccinationCertificate: {
                  isApplied: false,
                  hasServiceIncluded: true,
                  expectedDate: '2024-05-23T07:29:55.799Z',
                  executionDate: null,
                  resultDate: null,
                  isRequired: true,
                  observation: '',
                  isPrint: false,
                  user: '',
                },
                healthCertificate: {
                  isApplied: true,
                  hasServiceIncluded: true,
                  expectedDate: '2022-06-01T00:00:00.000Z',
                  executionDate: '2022-05-30T00:00:00.000Z',
                  resultDate: '2022-05-31T00:00:00.000Z',
                  isRequired: false,
                  observation: 'All documentation is in order.',
                  isPrint: false,
                  user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                },
                chipCertificate: {
                  isApplied: false,
                  hasServiceIncluded: true,
                  expectedDate: '2024-05-23T07:29:55.799Z',
                  executionDate: null,
                  resultDate: null,
                  isRequired: true,
                  observation: '',
                  isPrint: false,
                  user: '',
                },
                senasaDocuments: {
                  isApplied: true,
                  hasServiceIncluded: true,
                  expectedDate: '2022-06-01T00:00:00.000Z',
                  executionDate: '2022-05-30T00:00:00.000Z',
                  resultDate: '2022-05-31T00:00:00.000Z',
                  isRequired: false,
                  observation: 'All documentation is in order.',
                  isPrint: false,
                  user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                },
                rabiesSeroLogicalTest: {
                  isApplied: false,
                  hasServiceIncluded: true,
                  expectedDate: '2024-05-23T07:29:55.799Z',
                  executionDate: null,
                  resultDate: null,
                  isRequired: true,
                  observation: '',
                  isPrint: false,
                  user: '',
                },
                importLicense: {
                  isApplied: true,
                  hasServiceIncluded: true,
                  expectedDate: '2022-06-01T00:00:00.000Z',
                  executionDate: '2022-05-30T00:00:00.000Z',
                  resultDate: '2022-05-31T00:00:00.000Z',
                  isRequired: false,
                  observation: 'All documentation is in order.',
                  isPrint: false,
                  user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                },
                emotionalSupportCertificate: {
                  isApplied: true,
                  hasServiceIncluded: true,
                  expectedDate: '2022-06-01T00:00:00.000Z',
                  executionDate: '2022-05-30T00:00:00.000Z',
                  resultDate: '2022-05-31T00:00:00.000Z',
                  isRequired: false,
                  observation: 'All documentation is in order.',
                  isPrint: false,
                  user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                },
              },
              cage: {
                status: 'completed',
                hasServiceIncluded: true,
                chosen: {
                  modelCage: 'Deluxe Pet Carrier',
                  typeCage: 'Soft-sided',
                  dimensionsCage: '18 x 12 x 12 inches',
                  user: '',
                },
                confirmation: true,
                petTravelAcquisition: true,
                isCabinTransporting: false,
              },
              travel: {
                status: 'completed',
                hasServiceIncluded: false,
                hasServiceAccompanied: false,
                typeTraveling: 'accompanied',
                airlineReservation: {
                  code: 'A001',
                  flightNumber: '4005',
                  departureAirport: 'Lima, Peru',
                  destinationAirport: 'Buenos aires',
                  departureDate: '2022-06-01T00:00:00.000Z',
                  itinerary: '',
                  arrivalDate: '2022-06-01T00:00:00.000Z',
                  archive: '',
                  user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                },
                petPerCharge: {
                  name: 'pedro',
                  document: 'D.N.I.',
                  documentNumber: '123456789',
                  phone: '51939130496',
                  email: 'pedro@gmail.com',
                },
                accompaniedPet: {
                  name: 'pedro',
                  document: 'D.N.I.',
                  documentNumber: '123456789',
                  phone: '51939130496',
                  email: 'pedro@gmail.com',
                  direction: 'Turin 457',
                  district: 'San martin de porres',
                  province: 'Lima',
                  department: 'Lima',
                  image: 'user.png',
                },
                destination: {
                  countryDestination: 'España',
                  cityDestination: 'Barcelona',
                  directionDestination: 'Paseo de gracia',
                },
                guideNumber: '',
                observation: '',
              },
              pet: {
                id: 'eacec100-1552-4712-841c-eb1f68cc13d6',
                name: 'Terminal 01',
                race: 'Mestizo',
                gender: 'male',
                birthDate: '2024-05-24T11:55:09.571Z',
                chip: '',
                chipDate: null,
                color: 'Blanco',
                image: '',
                country: 'Perú',
                type: 'Canino',
                sterilized: 'No',
                status: 'active',
                adopter: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                isBrachycephalic: false,
                isPotentiallyDangerous: false,
                topico: {
                  chip: {
                    hasIncluded: false,
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                  },
                  vaccination: {
                    hasIncluded: false,
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                  },
                  rabiesVaccination: {
                    hasIncluded: false,
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                  },
                  rabiesReVaccination: {
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                  },
                  takingSampleSerologicalTest: {
                    executed: false,
                    date: null,
                    description: '',
                    observation: '',
                    typeSample: '',
                    user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                  },
                  _id: '66508031d086871037003832',
                },
                user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                cageRecommendation: {
                  modelCage: '',
                  typeCage: '',
                  dimensionsCage: '',
                  _id: '66508031d086871037003833',
                },
                measurementsAndWeight: {
                  weight: 0,
                  height: 0,
                  width: 0,
                  length: 0,
                  _id: '66508031d086871037003834',
                },
              },
              user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
              topico: {
                chip: {
                  hasIncluded: true,
                  executed: true,
                  date: '2022-01-01T00:00:00.000Z',
                  description: 'Chip contract description',
                  observation: 'Chip contract observation',
                  user: '09cccd46-e15e-4d06-8159-e1325cbd0c04',
                },
                vaccination: {
                  hasIncluded: false,
                  executed: false,
                  date: null,
                  description: '',
                  observation: '',
                  user: '',
                },
                rabiesVaccination: {
                  hasIncluded: false,
                  executed: false,
                  date: null,
                  description: '',
                  observation: '',
                  user: '',
                },
                rabiesReVaccination: {
                  executed: false,
                  date: null,
                  description: '',
                  observation: '',
                  user: '',
                },
                chipReview: {
                  executed: false,
                  date: null,
                  description: '',
                  observation: '',
                  user: '',
                },
                takingSampleSerologicalTest: {
                  executed: false,
                  date: null,
                  description: '',
                  observation: '',
                  typeSample: '',
                  user: '',
                },
              },
            },
          },
        },
      },
    }),
  );
}
